name: Database
abbreviation: db
checker: PragmaRX\Health\Checkers\Database
notify: true
column_size: 3
targets:
  - companies:
      type: "find_first_model"
      models:
        - "App\\Models\\Company\\Company"
  - "query speed":
      type: "raw_query"
      connection: "default"
      query: "select * from companies"
      maximum_time: 0.05
      error_message: "Query took %sms when it should have last at most %sms"
