version: '2.4'
services:
  auth:
    image: $JOB_IMAGE_NAME_DEV
    environment: 
      - PORT=3001
      - TOKEN_KEY=aeACze2XCnk5MrQMXhxBYLJMYY8Ejmev
      - APP_ENV=local
      - DB_HOST=mysql-testing
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      mysql-testing:
        condition: service_healthy

  mysql-testing:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
