name: API i-am-alive
abbreviation: apichecker
checker: PragmaRX\Health\Checkers\Http
notify: true
column_size: 3
timeout_message: "[TIMEOUT] A request to %s took %s seconds. Timeout is set to %s seconds."
connection_timeout: 2
roundtrip_timeout: 5
targets:
  - default:
      urls:
        - http://charts-api/api/v1/i-am-alive:
            method: GET
