version: '3.8'
services: 
  load-balancer:
    volumes:
      - ./config/load-balancer.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:3000

  gateway:
    volumes: 
      - ./stock-pickr-gateway/:/usr/src
    ports:
      - "3100"
    environment: 
      - PORT=3100
      - AUTH_SERVICE_HOST=http://auth:3000/
      - COMPANIES_SERVICE_HOST=http://companies-api/
      - MARKET_DATA_SERVICE_HOST=http://market-data-api/
      - CHARTS_SERVICE_HOST=http://charts-api/
      - METRICS_SERVICE_HOST=http://metrics-api/
      - QUERIES_SERVICE_HOST=http://company-query-api/
      - COMPANY_PROVIDER_SERVICE_HOST=http://company-provider-api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
      - REDIS_SCHEME=tcp

  companies:
    volumes: 
      - ./stock-pickr-companies:/usr/local/src/companies
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=companies
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  companies-api:
    ports:
      - 8000:80
    volumes:
      - ./stock-pickr-companies:/usr/local/src/companies
      - ./stock-pickr-companies/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  companies-worker:
    volumes: 
      - ./stock-pickr-companies:/usr/local/src/companies
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=companies
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
        
  charts:
    volumes: 
      - ./stock-pickr-charts:/usr/local/src/charts
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=charts
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  charts-api:
    ports:
      - 8004:80
    volumes:
      - ./stock-pickr-charts:/usr/local/src/charts
      - ./stock-pickr-charts/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  charts-worker:
    volumes: 
      - ./stock-pickr-charts:/usr/local/src/charts
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=charts
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  market-data:
    volumes: 
      - ./stock-pickr-market-data:/usr/local/src/market-data
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=market-data
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  market-data-api:
    ports:
      - 8005:80
    volumes:
      - ./stock-pickr-market-data:/usr/local/src/market-data
      - ./stock-pickr-market-data/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  market-data-worker:
    volumes: 
      - ./stock-pickr-market-data:/usr/local/src/market-data
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=market-data
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  scheduler:
    volumes: 
      - ./stock-pickr-scheduler:/usr/local/src/scheduler
    environment: 
      - COMPANY_PROVIDER_SERVICE_URL=http://company-provider-api/api/v1/
      - SCHEDULER_LOG_OUTPUT=/proc/1/fd/1
      - APP_ENV=local
      - APP_KEY=base64:bqNRzRasABLEjxidHLmncfDtBYFxcZ4j6lNGvfQyOZI=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=scheduler
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
  
  scheduler-worker:
    volumes: 
      - ./stock-pickr-scheduler:/usr/local/src/scheduler
    environment: 
      - COMPANY_PROVIDER_SERVICE_URL=http://company-provider-api/api/v1/
      - APP_ENV=local
      - APP_KEY=base64:bqNRzRasABLEjxidHLmncfDtBYFxcZ4j6lNGvfQyOZI=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=scheduler
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  company-provider:
    volumes: 
      - ./stock-pickr-company-provider:/usr/local/src/company-provider
    environment: 
      - FINNHUB_API_URL=$SP_FINNHUB_API_URL
      - FINNHUB_API_TOKEN=$SP_FINNHUB_API_TOKEN
      - USE_PRIORITY_TICKERS=false
      - APP_ENV=local
      - APP_KEY=base64:EOs/nvVTIjulSqmfZnLFb5hTlStPmfHHtGqQCtg4bB4=
      - APP_DEBUG=true
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  company-provider-api:
    ports:
      - 8002:80
    volumes:
      - ./stock-pickr-company-provider:/usr/local/src/company-provider
      - ./stock-pickr-company-provider/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  auth:
    volumes: 
      - ./stock-pickr-auth:/usr/local/src/auth
    environment: 
      - PORT=3000
      - TOKEN_KEY=aeACze2XCnk5MrQMXhxBYLJMYY8Ejmev
      - NODE_ENV=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=auth
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
    ports:
      - 8006:3000
    
  metrics:
    volumes: 
      - ./stock-pickr-metrics:/usr/local/src/metrics
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=metrics
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  metrics-api:
    ports:
      - 8007:80
    volumes:
      - ./stock-pickr-metrics:/usr/local/src/metrics
      - ./stock-pickr-metrics/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  metrics-worker:
    volumes: 
      - ./stock-pickr-metrics:/usr/local/src/metrics
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=metrics
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  company-query:
    volumes: 
      - ./stock-pickr-company-query:/usr/local/src/company-query
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=company-query
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  company-query-api:
    ports:
      - 8008:80
    volumes:
      - ./stock-pickr-company-query:/usr/local/src/company-query
      - ./stock-pickr-company-query/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  company-query-worker:
    volumes: 
      - ./stock-pickr-company-query:/usr/local/src/company-query
    environment: 
      - APP_ENV=local
      - APP_KEY=base64:eyQMQLqq4lz2hIj/pMcJ77QxYNHfd7PfQdysV+/niKc=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=company-query
      - DB_USERNAME=root
      - DB_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - REDIS_SCHEME=tcp
      - REDIS_CONSUMER_MODE=only-new-events
      - CACHE_DRIVER=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

  fe:
    ports:
      - 4000:8080
    volumes:
      - ./stock-pickr-fe:/usr/local/src
    environment:
      VUE_APP_API_BASE_URL: http://localhost:3000/api/v1

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=DfUfZk4zG9xDxCAm4PMv2sKymqbDqY4D5zJFvqQ2
    ports:
      - 33060:3306
    volumes:
      - ./mysqldata:/var/lib/mysql

  redis:
    ports:
      - 63790:6379
    volumes:
      - ./redisdata:/data

  phpmyadmin:
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql