name: Database
abbreviation: db
checker: PragmaRX\Health\Checkers\Database
notify: true
column_size: 3
targets:
  - chart_data:
      type: "find_first_model"
      models:
        - "App\\Models\\ChartData"
  - "query speed":
      type: "raw_query"
      connection: "default"
      query: "select * from chart_data"
      maximum_time: 0.05
      error_message: "Query took %sms when it should have last at most %sms"
